name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Install just
      uses: extractions/setup-just@v1
    - name: Check module dependencies
      run: just mod
    - name: Build source
      run: just build
    - name: Test source
      run: just test '-v -coverprofile=/tmp/cover.out'
    - name: Vet source
      run: just vet
    - name: Build, run examples
      run: |
        just build-examples
        ./bin/full_example || true
    - name: Upload code coverage
      uses: codecov/codecov-action@v3
      with:
        files: /tmp/cover.out

  # The GitHub action, securego/gosec, doesn't seem to work properly when it's
  # preceded by another action that supplies the env var, GOROOT. Example error:
  #
  #   loading files from package ".": err: exit status 2: stderr: go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.17.7/x64
  #
  # As a workaround, do this security scan separately.
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: --tests ./...
