name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Check module dependencies
      run: make mod
    - name: Build source
      run: make build
    - name: Test source
      run: make test ARGS="-v -coverprofile=/tmp/cover.out"
    - name: Vet source
      run: make vet
    - name: Build, run examples
      run: |
        make build-examples
        ./bin/full_example || true
    - name: Upload code coverage
      uses: codecov/codecov-action@v3
      with:
        files: /tmp/cover.out

  # The GitHub action, securego/gosec, doesn't seem to work properly when it's
  # preceded by another action that supplies the env var, GOROOT. Example error:
  #
  #   loading files from package ".": err: exit status 2: stderr: go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.17.7/x64
  #
  # As a workaround, do this security scan separately.
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: --tests ./...
